Repository pgaskin/NickelMenu, pull requests merged in 2020-06, with the labels that each got.

#37 Implement NM_UNINSTALL_CONFIGDIR build option
  .drone.yml
  Makefile
  src/config.c
  src/config.h
  src/init.c
Labels: feature

#38 Implement nickel_open action
  res/doc
  src/action.h
  src/action_cc.cc
Labels: action, action/new, feature

#41 Use macro for setting library name in log
  src/util.h
Labels: enhancement

#44 Implement nickel_misc:home action
  res/doc
  src/action_cc.cc
Labels: action, action/new-option, feature

#46 Implement nickel_wifi action
  res/doc
  src/action.h
  src/action_cc.cc
Labels: action, action/new, feature

#45 Better menu item injection
  src/menu.cc
Labels: enhancement

#50 Switch to new method for nickel_extras:web_browser and implement url/css options
  res/doc
  src/action_cc.cc
Labels: action, action/new-option, feature

#52 Implement option to set values for nickel_setting:* explicitly
  res/doc
  src/action_cc.cc
Labels: action, action/new-option, feature

#47 Implement config file reloading and improve the config parser
  src/config.c
  src/config.h
  src/init.c
  src/init.h
  src/menu.cc
  src/menu.h
Labels: feature

#40 Hide (nearly) all symbols by default
  Makefile
  src/dlhook.h
  src/failsafe.h
  src/menu.cc
  src/menu.h
  src/util.h
Labels: enhancement

#55 Implement generator updates
  src/config.c
  src/config.h
  src/generator.c
  src/generator.h
  src/generator_c.c
  src/init.c
Labels: enhancement

#58 Fix reloaded config only propagating to new menus or the first existing one
  src/init.c
  src/init.h
  src/menu.cc
Labels: bug, bug/unreleased
